spring:
  application:
    name: students-SpringProject
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
